image: mcr.microsoft.com/dotnet/sdk:9.0 # << DÒNG NÀY LÀ BẮT BUỘC

stages:
  - analyze
  - build
  - test
  - publish

variables:
  # --- BIẾN ĐỂ LINH HOẠT ĐƯỜNG DẪN ---
  SOLUTION_FOLDER_NAME: "WEB_CONG_THUC"
  MAIN_PROJECT_NAME: "WEB_CONG_THUC"

  # --- ĐƯỜNG DẪN ĐỘNG ---
  SOLUTION_FILE_PATH: "./${SOLUTION_FOLDER_NAME}/${SOLUTION_FOLDER_NAME}.sln"
  MAIN_PROJECT_BIN_PATH: "./${SOLUTION_FOLDER_NAME}/${MAIN_PROJECT_NAME}/bin"
  MAIN_PROJECT_FILE_PATH: "./${SOLUTION_FOLDER_NAME}/${MAIN_PROJECT_NAME}/${MAIN_PROJECT_NAME}.csproj"

  # --- BIẾN GỐC CỦA BẠN ---
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  BUILD_PATH: "build_output"

before_script:
  - echo "Đang chuẩn bị môi trường CI/CD..."
  - dotnet --version
  - dotnet restore "${SOLUTION_FILE_PATH}"

analyze:
  stage: analyze
  script:
    - echo "Chạy .NET Analyzers..."
    - dotnet build "${SOLUTION_FILE_PATH}" --configuration Release /warnaserror
  artifacts:
    paths:
      - "${MAIN_PROJECT_BIN_PATH}"
    expire_in: 1 day

build:
  stage: build
  script:
    - echo "Bắt đầu build ứng dụng..."
    - dotnet build "${SOLUTION_FILE_PATH}" --configuration Release
  artifacts:
    paths:
      - "${MAIN_PROJECT_BIN_PATH}"
    expire_in: 1 day

run_all_tests:
  stage: test
  script:
    - echo "Chạy tất cả unit test trong solution..."
    - dotnet test "${SOLUTION_FILE_PATH}" --configuration Release --logger trx --results-directory TestResults
  artifacts:
    paths:
      - TestResults/
    when: always

publish:
  stage: publish
  script:
    - echo "Đóng gói ứng dụng..."
    - dotnet publish "${MAIN_PROJECT_FILE_PATH}" -c Release -o $BUILD_PATH
  artifacts:
    paths:
      - $BUILD_PATH/
    expire_in: 1 week